[package]
name = "gazpacho"
version = "0.1.0"
authors = ["Andrey Cherkashin <andoriyu@gmail.com>"]
edition = "2018"

[dependencies]
uclicious = "0.1.2"
getset = "0.1.0"
strum = "0.18.0"
strum_macros = "0.18.0"
regex = "1"
libzetta = "0.2.1"
chrono = "0.4.11"
libc = "0.2.68"
zstd = "0.5.1"
ssh2 = "0.8.0"
filedescriptor = "0.7.1"
